- name: conditions in ansible
  hosts: localhost
  become: yes
  tasks: 
    - name: print apple Price
      ansible.builtin.debug:
        msg: Price of apple is 1$
      when: fruit == "apple"

    - name: Print orange Price
      ansible.builtin.debug:
        msg: Price of orange is 2$
      when: fruit == "orange"