- name: variables declaration learning
  hosts: localhost
  become: yes
  vars:
    var1: play level variable
  tasks:
    - name: print a variable
      ansible.builtin.debug:
        msg: "variable declared is {{ var1 }}"

    - name: print task level variable
      vars:
        var1: task level variable
      ansible.builtin.debug:
        msg: "variable declared is {{ var1 }}"



- name: variable declaration on roles
  hosts: localhost
  become: yes
  roles:
    - demo-variables

- name: conditions demo on variables
  hosts: localhost
  become: yes
  tasks:
    - name: print apple price
      ansible.builtin.debug:
        msg: "apple price is 1$"
      when: var == "apple"