# - name: learn ansible
#   hosts: localhost
#   roles:
#    - demo

# - name: learn ansible
#   hosts: localhost
#   vars:
#     var1: play level variables
#   tasks:
#    - name: print play level variables
#      ansible.builtin.debug:
#        msg: "variable level is {{var1}}"

#    - name: print task level variables
#      vars:
#        var1: task level variables
#      ansible.builtin.debug:
#        msg: "variable level is {{var1}}"



- name: print free memory
  hosts: localhost
  tasks:
    - name: print total memory
      ansible.builtin.shell: free
      register: free

    - name: print free memory
      ansible.builtin.debug:
        msg: "print free memory:{{free}}"