- name: variables declaration learning
  hosts: localhost
  become: yes
  vars:
    var1: play level variable
  tasks:
    - name: print a variable
      ansible.builtin.debug:
        msg: "variable declared is {{ var1 }}"

    - nane: print task level variable
      var1: task level variable
      ansible.builtin.debug:
        msg: "variable declared is {{ var1 }}"