- name: print free memory
  hosts: localhost
  become: yes
  tasks:
    - name: get free memory
      ansible.builtin.shell: free
      register: free
    - name: print free memory
      ansible.builtin.debug:
        msg: free