- name: print free memory
  hosts: localhost
  become: yes
  tasks:
    - name: get free memory
      ansible.builtin.shell: free | grep Mem | awk '{print$2}'
      register: total
    - name: print free memory
      ansible.builtin.debug:
        msg: "{{ total }}"