- name: print free memory
  hosts: localhost
  become: yes
  tasks:
    - name: get memory status
      ansible.builtin.shell: free | grep Mem | xargs
      register: Free
    - name: store details of memory
      ansible.builtin.set_fact:
        FREE: "{{ Free.stdout | split(' ') }}"
    - name: print mem status
      ansible.builtin.debug:
        msg: "{{ FREE }}"
    - name: store total, used, free memory available
      ansible.builtin.set_fact:
        TOTAL: "{{ FREE[1] | int }}"
        USED: "{{ FREE[2] | int }}"
        FREE: "{{ FREE[3] | int }}"
    - name: print used memory percentage
      ansible.builtin.set_fact:
        used_mem_perc: "{{ 100 - (FREE|int / TOTAL|int * 100) }}"

    - name: memory status red
      ansible.builtin.debug:
        msg: \033[31mMemory status is red\033[0m
      when: used_mem_perc | int > 70

    - name: memory status orange
      ansible.builtin.debug:
        msg: \033[33mMemory status is orange\033[0m
      when: used_mem_perc | int > 50 & used_mem_perc | int < 70
    
    - name: memory status is green
      ansible.builtin.debug:
        msg: \033[32mMemory status is green\033[0m
      when: used_mem_perc | int < 50