- name: print free memory
  hosts: localhost
  become: yes
  tasks:
    - name: get memory status
      ansible.builtin.shell: free | grep Mem | awk '{print$2}'
      register: total
    - name: print total memory
      ansible.builtin.debug:
        msg: "{{ total.stdout }}"