- name: print free memory
  hosts: localhost
  become: yes
  tasks:
    - name: get memory status
      ansible.builtin.shell: free | grep Mem | xargs
      register: Free
    - name: print total memory
      ansible.builtin.set_fact:
        FREE: "{{ Free.stdout | split(' ') }}"
    # - name: get used memory status
    #   ansible.builtin.shell: free | grep Mem | awk '{print$3}'
    #   register: used
    # - name: print used memory
    #   ansible.builtin.debug:
    #     msg: "{{ used.stdout }}"
    # - name: print free memory status
    #   ansible.builtin.debug:
    #     msg: "{{ total - used }}"