- name: print free memory
  hosts: localhost
  become: yes
  tasks:
    - name: get memory status
      ansible.builtin.shell: free | grep Mem
      register: total
    - name: print total memory
      ansible.builtin.debug:
        msg: "{{ total.stdout }}"
    # - name: get used memory status
    #   ansible.builtin.shell: free | grep Mem | awk '{print$3}'
    #   register: used
    # - name: print used memory
    #   ansible.builtin.debug:
    #     msg: "{{ used.stdout }}"
    # - name: print free memory status
    #   ansible.builtin.debug:
    #     msg: "{{ total - used }}"