- name: print free memory
  hosts: localhost
  become: yes
  tasks:
    # - name: get memory status
    #   ansible.builtin.shell: free | grep Mem | xargs
    #   register: Free
    # - name: store details of memory
    #   ansible.builtin.set_fact:
    #     FREE: "{{ Free.stdout | split(' ') }}"
    # - name: print mem status
    #   ansible.builtin.debug:
    #     msg: "{{ FREE }}"
    # - name: store total, used, free memory available
    #   ansible.builtin.set_fact:
    #     TOTAL: "{{ FREE[1]  }}"
    #     USED: "{{ FREE[2]  }}"
    #     FREE: "{{ FREE[3]  }}"
    # - name: print used memory percentage
    #   ansible.builtin.set_fact:
    #     used_mem_perc: "{{ 100 - (FREE / TOTAL * 100) }}"
      # ansible.builtin.debug:
      #   msg: "Memory status is red"
      # when: used_mem_perc  > 70
    # - name: memory status orange
    #   ansible.builtin.debug:
    #     msg: "Memory status is orange"
    #   when: used_mem_perc  > 50 and used_mem_perc  < 70

    # - name: memory status is green
    #   ansible.builtin.debug:
    #     msg: "Memory status is green"
    #   when: used_mem_perc  < 50

    - name: get metadata about node
      ansible.builtin.setup:

    - name: store used mem percentage
      ansible.builtin.debug:
        msg: (ansible_memory_mb["real"]["free"] / ansible_memory_mb["real"]["total"] ) * 100
      register: free_perc

    - name: memory status is red
      ansible.builtin.debug:
        msg: Memory status is good
      when: (100 - free_perc ) < 50

    - name: memory status orange
      ansible.builtin.debug:
        msg: Memory status is orange
      when: free_perc>50 and free_perc<70
     
    - name: Memory status is green
      ansible.builtin.debug:
        msg: Memory status is green
      when: free_perc> 50