- name: Print free
  hosts: localhost
  become: yes
  tasks:
    - name: Get memory
      ansible.builtin.shell: free | grep Mem | xargs
      register: free

    - name: Print free memory
      ansible.builtin.set_fact:
        FREE: "{{free.stdout | split(' ')}}"

    - name: Print values according to the index
      ansible.builtin.set_fact:
        total: "{{FREE[1]}}"
        free: "{{FREE[3]}}"
        freePercentage: "{{FREE[3]|int / FREE[1]|int * 100}}"
        usedPercentage: "{{ 100 - (FREE[3]|int / FREE[1]|int * 100)}}"

    - name: Print output of a command
      ansible.builtin.debug:
        msg: "{{freePercentage}}"

    - name: Print status of used memory
      ansible.builtin.debug:
        msg: 