- name: task level vars
  hosts: localhost
  become: yes
  vars:
    firstVariable: Sri
  tasks:
    - name: Print task variable
      vars:
        firstVariable: Harsha
      ansible.builtin.debug:
        msg: "{{ firstVariable }}"

    - name: Print play variable
      ansible.builtin.debug:
        msg: "{{ firstVariable }}"
      